# permissions for end users to edit externaldns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externaldns-editor
rules:
- apiGroups:
  - externaldns.olm.openshift.io
  resources:
  - externaldns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - externaldns.olm.openshift.io
  resources:
  - externaldns/status
  verbs:
  - get
